# Conditions

In [2]:
if True: # indentiation is always 4 space
       print('Data Science')

Data Science


In [3]:
if True:
    print('ds')

ds


In [6]:
if False:
    print('Data Science')
print('bye for now')

bye for now


In [8]:
if True:   # indentiation is always 4 spaces
    print('data Science')
print('bye for now')

data Science
bye for now


In [9]:
if False: # indentiation is always 4 spaces
    print('Data Science')
else:
    print('bye for now')

bye for now


In [10]:
#to print only even number
x = 4
r = x % 2 

if r == 0:
    print('Even number')

Even number


In [13]:
# to print only even number
x = 5
r = x % 2 

if r == 0:
    print('Even number')

In [14]:
x = 5
r = x % 2 

if r == 0:
    print('Even number')
print('odd number')

odd number


In [15]:
x = 6
r = x % 2 

if r == 0:
    print('Even number')
print('odd number')

Even number
odd number


In [16]:
x = 10
r = x % 2 

if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

Even number


In [17]:
x = 11
r = x % 2 

if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

odd number


In [18]:
x = 11
r = x % 2 

if r == 0:
    print('Even number')
else:
    print('odd number')

odd number


In [19]:
x = 23
r = x % 2 

if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

odd number


In [20]:
x = 17
r = x % 2 

if r == 0:
    print('Even number')
    
if r != 0:
    print('odd number')

odd number


In [21]:
x = 5
r = x % 2

if r == 0:
    print('Even number')
else:
    print('Odd Number')

Odd Number


In [22]:
x = 4
r = x % 2

if r == 0:
    print('Even number')
else:
    print('Odd Number')

Even number


In [23]:
x = 3
r = x % 2

if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
  
else:
    print('Odd Number')

Odd Number


In [24]:
x = 4
r = x % 2

if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
     
else:
    print('Odd Number')

Even number


In [25]:
x = 4
r = x % 2

if r == 0:
    print('Even number')
    if x>5 :
        print('greater number')
    else:
       print('not greater ')
else:
    print('odd number')

Even number
not greater 


In [26]:
x = 6
r = x % 2

if r == 0:
    print('Even number')
    if x>5 :
        print('greater number')
    else:
        print('not greater ')
        
else:
    print('odd number')

Even number
greater number


In [27]:
# when you use if it will check all condition but if we mention elif then it wont check all condition
# when we use if condiction it will check all every block of code better debug in pychame
#you can debug with value 1 & d for both if & elif 
x = 2

if x == 1:
    print('one')
if x == 2:
    print('Two')
if x == 3:
    print('Three')
if x == 4:
    print('four')

Two


In [28]:
# elif it wont check till the block once you find the output it wont go to next line
# you can try with multiple parameter 1, 2 & 3 value in x 

x = 4

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

four


In [29]:
x = 7

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

In [30]:
x = 7

if(x == 1):
    print('one')
    
    
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
    
else:
    print('wrong output')

wrong output


In [31]:
x = 4

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
else:
    print('wrong output')

four


In [32]:
x = 10

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
   
else:
    print('wrong output')

wrong output


In [33]:
#short hand if 
a = 30
b = 20
if a > b: print("a is greater than b")

a is greater than b


In [34]:
print('data science')
print('data science')
print('data science')
print('data science')    
print('data science')

data science
data science
data science
data science
data science


In [35]:
i = 1          # initializing

while i<=5:    # condition
    print('data science')
    i = i + 1  # increment

data science
data science
data science
data science
data science


In [36]:
i = 5          # initializing

while i>=1:    # condition
    print('data science')
    i = i - 1  # decrement

data science
data science
data science
data science
data science


In [37]:
i = 1         # initializing
while i<=5:    # condition
    print('data science : ', i)
    i = i + 1  # increment

data science :  1
data science :  2
data science :  3
data science :  4
data science :  5


In [38]:
i = 5          # initializing
while i>=1:    # condition
    print('data science :',i)
    i = i - 1  # decrement

data science : 5
data science : 4
data science : 3
data science : 2
data science : 1


In [39]:
i = 1

while i<=5:
    print('data science') # when we mention end then new line will not create
    j = 1
    while j<=4:
        print('technology')
        j = j + 1
        
    i = i + 1
    print()
    
    # the output which we got is very lengty but how to make them one line lets refer to below code

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology



In [40]:
i = 1
while i<=5:
    print(' datascience', end = "") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="")
        j = j + 1
        
    i = i + 1
    print()

 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology
 datascience technology technology technology technology


In [41]:
# lets use while loop usig some numbers
i = 1

while i <= 2 :
    j = 0
    while  j <= 2 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 
0 2 4 


In [42]:
# lets use while loop usig some numbers
i = 1
while i <= 4 :
    j = 0
    while  j <= 3 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


In [ ]:
FOR LOOP  -
normally while loop it work with iteration or certaion some condition but for loop it will work with sequence (list, string,int)

In [43]:
name = 'nit'

for i in name:
    print(i)

n
i
t


In [44]:
name1 = [1,3.5,'hallo'] #i want print the value individualy

for i in name1:
    print(i)

1
3.5
hallo


In [45]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [46]:
range(5)

range(0, 5)

In [47]:
for i in range(5):
    print(i)

0
1
2
3
4


In [48]:
for i in range(2,5):
    print(i)

2
3
4


In [49]:
for i in range(1,10,3):
    print(i)

1
4
7


In [50]:
# print the value which is divisible by 5 
for i in range(1,21):
    print(i)  

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [51]:
# print the value which is divisible by 5 

for i in range(1,51):
    
    if i%5==0 :
        print(i)

5
10
15
20
25
30
35
40
45
50


In [52]:
# print the value which is divisible by 5 i dont want that value 
for i in range(1,51):
    
    if i%5!=0 :
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49


In [ ]:
# LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
# Pass = skips block of code( function, class etc)
# Continue= skips 1 step/iteration during loop 
# Break= jumps out of the function/loop

In [53]:
# write the code user ask chocklet from vendor machne write the basic code 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1       

How many choclets you want:? 5


choclet
choclet
choclet
choclet
choclet


In [54]:
ava = 5 # the machine has only 5 choclet 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1   
# if you check the user wants 10 choclets  but availabe choclet is 5 but we got output as 10 choclet
# in this code we just declare but we dint apply any condition to it 

How many choclets you want:? 6


choclet
choclet
choclet
choclet
choclet
choclet


In [55]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets user want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets user want:? 2


choclet
choclet
bye for now


In [56]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        print('out of stock')
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets you want:? 3


choclet
choclet
choclet
bye for now


In [57]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [58]:
for i in range(1,11):
    if i == 6:
       break 
    print(i)

1
2
3
4
5


In [59]:
# in continue loop wont be terminate & exclue the assign number it give you entire output 

In [60]:
for i in range(1,11):
    if i == 3:
        continue 
    print(i)

1
2
4
5
6
7
8
9
10


In [61]:
for i in range(1,11):
    if i == 6:
        continue  
    print('hello :',i)

hello : 1
hello : 2
hello : 3
hello : 4
hello : 5
hello : 7
hello : 8
hello : 9
hello : 10


In [62]:
#PASS Statement - pass the code & it wont go ( code give you the error)

In [1]:
for i in range(1,11):

SyntaxError: incomplete input (1334445784.py, line 1)

In [2]:
for i in range(1,11):
    pass

In [5]:
for i in range(1,51):
    if i%3 ==0:
        print(i)
        print('end')

3
end
6
end
9
end
12
end
15
end
18
end
21
end
24
end
27
end
30
end
33
end
36
end
39
end
42
end
45
end
48
end


In [6]:
for i in range(1,54):
    if i%3 ==0:
        print(i)
    print('end')

end
end
3
end
end
end
6
end
end
end
9
end
end
end
12
end
end
end
15
end
end
end
18
end
end
end
21
end
end
end
24
end
end
end
27
end
end
end
30
end
end
end
33
end
end
end
36
end
end
end
39
end
end
end
42
end
end
end
45
end
end
end
48
end
end
end
51
end
end
end


In [26]:
for i in range(1,51):
    if i%3 == 0:
        print(i)
    print('end')

end
end
3
end
end
end
6
end
end
end
9
end
end
end
12
end
end
end
15
end
end
end
18
end
end
end
21
end
end
end
24
end
end
end
27
end
end
end
30
end
end
end
33
end
end
end
36
end
end
end
39
end
end
end
42
end
end
end
45
end
end
end
48
end
end
end


In [34]:
for i in range(1,54):
    if i%3 == 0:
          continue
    print(i)
print('end')

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
52
53
end


In [36]:
for i in range(1,54):
    if i%3 == 0:
        print(i)
print('end')

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
end


In [40]:
for i in range (1,51):
    if i%3 == 0 or i%5 ==0:
        print(i)
        #print('end')    
# it will skip all the value which is divisible by 3 or 5

3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50


In [39]:
for i in range (1,51):
    if i%3 == 0 or i%5 ==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [41]:
for i in range(1,50):
    if i%3 == 0 and i%5 == 0:
        continue
    print(i)
print('end')    
# when you apply and you wont get the value which is divisible by both 3 & 5 (15)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
47
48
49
end


In [42]:
# i dont want to print the values which are even numbers that means print only odd numbers

for i in range(1,51):
    
    if (i%2 == 0):
        #print('even')
        continue
    else:
        print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


In [43]:
# PRINTING PATTERN IN PYTHON

In [44]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [45]:
for i in range(1,5):
    i=i+1
    print('# # # # ')

# # # # 
# # # # 
# # # # 
# # # # 


In [46]:
for i in range(1,5):
    if i<=5:
        print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [47]:
for j in range(4):
    print('#')

#
#
#
#


In [48]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [49]:
for j in range(4):
    print('#', end=" ")

for j in range(4):
    print('#', end=" ")


# # # # # # # # 

In [50]:
for j in range(4):
    print('#', end=" ")
    
print()
    
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [51]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [52]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()
    # pease use debug mode in pycharm

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [53]:
for i in range(4):
    for j in range(i+1):
        print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [54]:
for i in range(1,5):
    print("# "*i)

# 
# # 
# # # 
# # # # 


In [55]:
for i in range(1,5):
    for j in range(4):
        if i>j:
            print("#",end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
for i in range(4):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  


In [58]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [59]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [60]:
for i in range(1,5):
    print("# "*(5-i))

# # # # 
# # # 
# # 
# 


In [61]:
nums = [12,15,18,21,26, 30, 40]

for num in nums:
    if num % 5 == 0:
        print(num) 

15
30
40


In [62]:
nums = [12,14,18,21,25,30,35]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
30
35


In [63]:
nums = [12,14,18,21,25,20]

for num in nums:
    if num % 5 == 0:
        print(num)

25
20


In [64]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [65]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [66]:
nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break 

10


In [67]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

In [68]:
nums = [7,14,18,21,23,27,29] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') #every iteration it cheking condition

Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found


In [69]:
nums = [7,14] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') #every iteration it cheking condition 

Number Not Found
Number Not Found


In [70]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found') # hear else we dont write in if block but we can write in for block only

Number Not Found


In [71]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [72]:
nums = [10,14,18,21,20,27,30] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [73]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [74]:
num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Not prime Number


In [75]:
num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Prime Number


In [76]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 12
Enter the next value 34
Enter the next value 23
Enter the next value 465
Enter the next value 6
Enter the next value 56


array('i', [34, 23, 465, 6, 56])


In [77]:
from array import * 
arr = array('i',[])

n = input('Enter the length of the array')

for i in range(5):
    x = input('Enter the next value')
    arr.append(x)
print(arr)

Enter the length of the array 2
Enter the next value 3


TypeError: 'str' object cannot be interpreted as an integer

In [78]:
# Way of creating array using numpy

In [79]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [80]:
print(arr.dtype)

int32


In [81]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [82]:
print(arr.dtype)

float64


In [83]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [84]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [85]:
import numpy as np

In [86]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [87]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [88]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [89]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [ ]:
import tkinter as tk
# Function to be called when the button is clicked
def on_button_click():
    label.config(text="Button clicked!")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Hello, Tkinter!")
label.pack(pady=20)

# Create a button widget
button = tk.Button(root, text="Click Me", command=on_button_click)
button.pack(pady=20)

# Run the application
root.mainloop()

In [ ]:
import tkinter as tk
from tkinter import messagebox

# Function to be called when the button is clicked
def on_button_click():
    user_input = entry.get()
    messagebox.showinfo("Information", f"You entered: {user_input}")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Enter something:")
label.pack(pady=10)

# Create a text entry widget
entry = tk.Entry(root, width=30)
entry.pack(pady=10)

# Create a button widget
button = tk.Button(root, text="Submit", command=on_button_click)
button.pack(pady=10)

# Run the application
root.mainloop()